branch-defaults:
  master:
    environment: py27-t2nano-vpc-2
environment-defaults:
  py27-t2nano-vpc-2:
    branch: null
    repository: null
global:
  application_name: iotd-python2
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/Python 2.7 running
    on 64bit Amazon Linux/2.3.2
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
